### ISSUE TITLE
GH Rate limiting

### ISSUE THREAD

**Issue by d-a-n42** [frenck/action-setup-lokalise#74]
First, thanks for providing this action to the community 👍 

The request in https://github.com/frenck/action-setup-lokalise/blob/main/action.yaml#L28 quickly runs into GHs API rate limiting. To avoid this, we should add a `token` input that allows users to provide their own access token to prevent rate-limiting issues:

> `curl -s --header 'Authorization: Bearer ${{ inputs.token }}' https://api.github.com/repos/lokalise/lokalise-cli-2-go/releases/latest | jq -r '.tag_name'`

Another idea would be to not fetch it for each usage - as the versions don't change that often - but hard code it and update the version regularly via an action in this repo. E.g. once a day:

```yaml
name: Update Lokalise Version
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  update-lokalise-cli-version:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest Lokalise version
        id: fetch-version
        run: |
          version=$(curl --silent "https://api.github.com/repos/lokalise/lokalise-cli-2-go/releases/latest" | jq -r .tag_name)
          echo "::set-output name=version::$version"

      - name: Setting Lokalise CLI version default to current version
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.inputs.version.default = "${{ steps.fetch-version.outputs.version }}"' -i action.yml

      - name: Commit and push if changes
        run: |
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m 'Update Lokalise version'; git push)
```

@frenck What do you think?
